### ISSUE TITLE
Python package structure

### ISSUE THREAD

**Issue by aremazeilles** [nickkluft/udbenchmark_PIs#1]
To get a more portable version of the code, it would be great organizing the code as a python package.

An example is availablhe [here](https://github.com/eurobench/pi_python_duration).
If you are not familiar with this, would you like me to support you in this?

Also, while trying to launch the code, I add difficulties with the library `kinpy`, that I had to clone locally to get it working.

Could you remind me what type of environment you are using for your development (Linux / windows)? I guess it is windows. How did you installed `kinpy` on your side?

**Comment by nickkluft** [comment]
Hi Anthony, 

Thanks for your input. I will try to convert it to a python package. I might need some help indeed, as I’m not familiar with this. 
The code is ready, but had not registered the fact that it should have an YAML output. I will try to fix your points/issues this week.

Best,
Nick

**Comment by nickkluft** [comment]
I have updated the code, which is now converted into python packages.
They run individually, so you need to install them separately. I still need to make some changes to match the input/output with the PI_ALGO doc.

Furthermore, I got some unexpected issues with the packaging in the pi_FPE, so I still need to work a bit on that. 

Hope the structure fits yours,
Nick

**Comment by aremazeilles** [comment]
Thanks
I am going to try your code, and make some suggestions through branches to be merged in your main branch. Are you familiar with this?

Once I will have checked all pi, I will close that issue.

**Comment by aremazeilles** [comment]
When I launch the fpe, I get the following issue:

```term
run_fpe PI_udbenchmark_github/tests/data/input/subject_04_jointTrajectories_01.csv PI_udbenchmark_github/tests/data/input/subject_04_comTrajectories_01.csv PI_udbenchmark_github/tests/data/input/subject_04_angMomentum_01.csv PI_udbenchmark_github/tests/data/input/subject_04_comItensor_01.csv PI_udbenchmark_github/tests/data/input/subject_04_gaitEvents_01 PI_udbenchmark_github/tests/data/input/subject_04_testbedLabel_01.yaml outfolder 
Retrieving gait events...
['0', '0', '1', '1.5']
Optimisation of foot placement estimator...
Traceback (most recent call last):
  File "/home/anthony/code/eurobench/udbenchmark/udbenchmark/venv/bin/run_fpe", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/anthony/code/eurobench/udbenchmark/udbenchmark/PI_udbenchmark_github/src/pi_FPE/script/run_fpe", line 7, in <module>
    sys.exit(main())
  File "/home/anthony/code/eurobench/udbenchmark/udbenchmark/PI_udbenchmark_github/src/pi_FPE/pi_FPE/footplacementestimator.py", line 234, in main
    print(fpe[tos])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices


Is it the error you were talking about? Can you double check the order of parameters eventually?
```

**Comment by nickkluft** [comment]
Hi Anthony, 

Should work now. I used the code:

run_fpe ./tests/data/input/subject_04_jointTrajectories_01.csv ./tests/data/input/subject_04_comTrajectories_01.csv ./tests/data/input/subject_04_angMomentum_01.csv ./tests/data/input/subject_04_comItensor_01.csv ./tests/data/input/subject_04_gaitEvents_01 ./tests/data/input/subject_04_testbedLabel_01.yaml ./tests/data/output

Best,
Nick

**Comment by aremazeilles** [comment]
Yep, now it works!

But we are missing in the [output reference folder](https://github.com/nickkluft/udbenchmark_PIs/tree/master/PI_udbenchmark_github/tests/data/output) the related PI file. Will put an issue for this
