### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SjoerdBruijn** [nickkluft/udbenchmark_PIs#11]
Hi, just browsing the code, looks good. I don't know too much python and how the whole system works, but I found a typo in udbenchmark_PIs/src/pi_FPE/pi_FPE/__init__.py 

on the last line, it reads: 
__all__ = ['clacFPE']
which should probably be
__all__ = ['calcFPE']

I was too lazy to branch and create a pull request.. ;-). 
Otherwise it looks impressive!

**Comment by nickkluft** [comment]
I corrected it. Thanks Sjoerd.
