### ISSUE TITLE
pi algo -> pi

### ISSUE THREAD

**Issue by aremazeilles** [nickkluft/udbenchmark_PIs#14]
Looking at the coherence in between the excel sheet and the data generated by the code

PI Algorithm `pi_fpe`is said to generate `[pi_FPE_ap.yaml,pi_FPE_ml.yaml, pi_l_MOS_ap.yaml, pi_l_MOS_ml.yaml, pi_r_MOS_ap.yaml, pi_r_MOS_ml.yaml]`.
The two  first ones PIs are not described in the excel sheet. We find a PI pi_fpe that is not used. Should it be duplicated?

**Comment by nickkluft** [comment]
The excel sheet has been updated. The '_ap' and '_ml' extensions indicate in which direction the PI is calculated (_ap: anteroposterior direction, _ml: mediolateral direction). Hope it works for you now.

**Comment by aremazeilles** [comment]
Ok, good

It seems the `pi_r_fpm` is not in the excel anymore. I guess I can copy `pi_l_fpm`, updating left with right?

**Comment by nickkluft** [comment]
Yes, you can.

**Comment by aremazeilles** [comment]
Done
