### ISSUE TITLE
vector results value are not well formatted

### ISSUE THREAD

**Issue by alfonsotecnalia** [nickkluft/udbenchmark_PIs#19]
Here it is an example of a result file of type vector:

```
---
type: 'vector'
values:
 -0.17218
 -0.16316
 -0.14997
 -0.15348
 -0.14597
 -0.13297
 -0.14612
....
```

The content in values is interpreted as a string. In order to be interpreted as a list:

- put the values inside `[]` separated by `,`
- put `-` before each of the values. If the already existing `-` character is not for expressing negative values, then it should be separated from the value: -0.17218 -> - 0.17218

**Comment by aremazeilles** [comment]
So that the current issue is that a space is missing in between the `-` and the number (assuming that the `-` is not referring to the minus sign), correct?

**Comment by alfonsotecnalia** [comment]
yes

**Comment by alfonsotecnalia** [comment]
Not only the scripts need to be modified but also the files in https://github.com/nickkluft/udbenchmark_PIs/tree/master/tests/data/output
