### ISSUE TITLE
Input file: check format

### ISSUE THREAD

**Issue by aremazeilles** [nickkluft/udbenchmark_PIs#7]
I am revising the input file format.
I noticed several issues. Maybe you prefer that we process with one issue per file?

**[subject_04_angMomentum_01.csv](https://github.com/nickkluft/udbenchmark_PIs/blob/master/PI_udbenchmark_github/tests/data/input/subject_04_angMomentum_01.csv)**

```csv
time,H_x,H_y,H_z,
0,NaN,NaN,NaN
10,-0.61625,-1.2077,-0.0088379
```
According to the [documentation](https://github.com/aremazeilles/eurobench_documentation/blob/master/data_format.adoc#65-angular-momentum-around-the-center-of-mass)

we should have:

* labels `x`, `y`, `z`
* time should be in sec
* no `Nan` line

**[subject_04_comItensor_01.csv](https://github.com/nickkluft/udbenchmark_PIs/blob/master/PI_udbenchmark_github/tests/data/input/subject_04_comItensor_01.csv)**

Is it related to the [inertia tensor](subject_04_comItensor_01.csv)?
If so, the filename should be something like: `subject_04_cominertiaTensor.csv`, or `subject_04_inertiaTensor.csv`. Also file content should follow the suggested labels and structure.

**[subject_04_comTrajectories_01.csv](https://github.com/nickkluft/udbenchmark_PIs/blob/master/PI_udbenchmark_github/tests/data/input/subject_04_comTrajectories_01.csv)**

I guess it is related to the [center of mass trajectory](https://github.com/aremazeilles/eurobench_documentation/blob/master/data_format.adoc#64-body-center-of-mass-3d-trajectory).

File should be named: `subject_04_comTrajectories_01.csv`.
Please follow the labels and units mentioned in the documentation

**[subject_04_gaitEvents_01](https://github.com/nickkluft/udbenchmark_PIs/blob/master/PI_udbenchmark_github/tests/data/input/subject_04_gaitEvents_01)**

Add .yaml to the filename. We may have to discuss the most appropriate format, but if we stick to the current [gait event format](https://github.com/aremazeilles/eurobench_documentation/blob/master/data_format.adoc#610-gait-events-file):

* No `"` around the value
* all value should go on one line per item, i.e something like:

```yaml
l_toe_off: [0.01, 1.55, 2.89, 4.08, 5.17, 6.15, 7.14, 8.13, 9.11, 10.12, 11.11, 12.1, ...]
l_heel_strike: [0.62, 2.09, 3.38, 4.53, 5.57, 6.56, 7.54, 8.52, 9.5, 10.51, ...]
r_toe_off: [0.87, 2.3, 3.51, 4.64, 5.66, 6.65, 7.63, 8.62,...]
r_heel_strike: [1.35, 2.74, 3.97, 5.05, 6.06,...]
```
**[subject_04_jointTrajectories_01.csv](https://github.com/nickkluft/udbenchmark_PIs/blob/master/PI_udbenchmark_github/tests/data/input/subject_04_jointTrajectories_01.csv)**

In the [documentation](https://github.com/aremazeilles/eurobench_documentation/blob/master/model.adoc#1-joint-centers) we have much less joint names that you have in file.
We do not have the label `thMetacarpalHeads`, `thfingertip`, `C7T1`, `MetTar1`, `MetTar2`, `MetaTars1`, `MetaTars5`, `PlatformLA`, `PlatformLB`, `PlatformRA`, `PlatformRB`, `T12L1`, `l_TTII`, `l_heel`, `r_TTII`, `r_heel`. Would you have a figure that could illustrate where are place these joints?

Given the name of  `PlatformLA`, `PlatformLB`, `PlatformRA`, `PlatformRB`, I am not sure this correspond to human joint. Can you confirm?

**[subject_04_testbedLabel_01.yaml](https://github.com/nickkluft/udbenchmark_PIs/blob/master/PI_udbenchmark_github/tests/data/input/subject_04_testbedLabel_01.yaml)**

File should have format:
```yaml
testbedlabel0: roll_0deg,
testbedlabel1: treadmill_1.5mps
```

**Comment by alfonsotecnalia** [comment]
Filenames should end with format_name.extension. No number before the file extension:
subject_04_jointTrajectories_01.csv -> subject_04_jointTrajectories.csv

If the number refers to a repetition, then:
subject_04_jointTrajectories_01.csv -> subject_04_run_01_jointTrajectories.csv

if the number refers to a condition/configuration of the testbed the:
subject_04_jointTrajectories_01.csv ->subject_04_cond_01_jointTrajectories_01.csv

Testbed configuration filename should be of the form `cond_C_testbed.yaml` being C the number of condition/configuration. If there is only one, `cond_C_` is not needed. Does the configuration depend on the subject? If not, then remove subject_04_ from the filename.

**Comment by aremazeilles** [comment]
Actually, input data file placed in the repo are meant to be used for the testing stage.
If we provide data of a single run, then there is no need to add anything more than the `file_type_tag.extension`

**Comment by alfonsotecnalia** [comment]
Just to take into account when data set provided (if provided)

**Comment by nickkluft** [comment]
I adjusted the files accordingly. 
Regarding the jointTrajectories l_TTII, l_heel, r_TTII, r_heel, are landmarks rather than joints (see figure). Where TTII stands for tip of the second toe, and heel stands for the tuborisity of the calcaneus.
The other joints are no requirements for running the code. 
![external-content duckduckgo](https://user-images.githubusercontent.com/29227422/94436884-4d1a6200-019d-11eb-9376-f04e3850961b.jpg)

**Comment by aremazeilles** [comment]
Looking at the [input data](https://github.com/nickkluft/udbenchmark_PIs/tree/master/tests/data/input), we nw only have:

```term
subject_04_cond_23_run_01_gaitEvents.yaml  subject_04_gaitEvents_01
```

It seems that you erased more files that you should hav. Is that correct?

**Comment by nickkluft** [comment]
Yes, I have renamed the files according the document. I have put new files on there today.
What should I do with missing values? Of course, I could  remove them but this will give jumps in the timestamp data?

**Comment by aremazeilles** [comment]
`run_fpe` requires a inertia tensor around COM. Did you upload that file as well?

**Comment by aremazeilles** [comment]
I also get prb calling `run_fpm`. Not sure which event file should be used, `subject_04_cond_23_run_01_gaitEvents.yaml` or `subject_04_gaitEvents_01`, and it works with none

**Comment by aremazeilles** [comment]
Sorry, `run_fpm` works with `subject_04_cond_23_run_01_gaitEvents.yaml`. 
There is thus just an issue for `run_fpe` that requires a `inertiaTensor` file.

Could you add it @nickkluft

**Comment by aremazeilles** [comment]
I think that most of the topics are mentioned in the #13 .
Regardings the jointReajectories additional landmarks, we extended documentation to permit using landmarks, as long as they are mentioned in the protocol documentation. So I would close this issue.
